Add missing includes.. without these I get a build failure with: CMakeFiles/robomongo.dir/robomongo/core/domain/MongoCollectionInfo.cpp.o: In function `Robomongo::MongoCollectionInfo::MongoCollectionInfo(mongo::BSONObj)': robomongo/src/robomongo/core/domain/MongoCollectionInfo.cpp:7: undefined reference to `mongo::BSONObj::getStringField(char const*) const' robomongo/src/robomongo/core/domain/MongoCollectionInfo.cpp:14: undefined reference to `mongo::BSONObj::getIntField(char const*) const'